trigger: none
pool: Agentpool
jobs:
 - job: job1
   displayName: string # Human-readable name for the job.
   pool: macpool
   dependsOn: agentpool
   steps:
     - task: CmdLine@1
       inputs:
        script: 'mac'
 - job: job2
   displayName: string # Human-readable name for the job.
   dependsOn: string 
   steps:

 - job: TerraformInt
   displayName: Init
   steps:
     - task: TerraformTaskV2@2
       
     
